**1. Import numpy and pandas libraries**

In [2]:
import pandas as pd
import numpy as np

In [3]:
#Test the code below by printing version of pandas and numpy
print('Pandas Version: '+pd.__version__)
print('Numpy Version: '+np.__version__)

Pandas Version: 1.5.1
Numpy Version: 1.23.4

**2. Load datasets**

In [4]:
# Read the data
Books = pd.read_csv('dataset/bx_271380_books.csv', on_bad_lines='skip', sep=';', encoding='latin-1')
Users = pd.read_csv('dataset/bx_278860_users.csv', on_bad_lines='skip', sep=';', encoding='latin-1')
Ratings = pd.read_csv('dataset/bx_1149781_book_ratings.csv', on_bad_lines='skip', sep=';', encoding='latin-1')

C:\Users\almud\AppData\Local\Temp\ipykernel_5768\1522618593.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  Books = pd.read_csv('dataset/bx_271380_books.csv', on_bad_lines='skip', sep=';', encoding='latin-1')

In [5]:
#Test the code below by printing the first 2 rows of each dataset
Books.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...

In [6]:
Users.head(2)

   User-ID                   Location   Age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

In [7]:
Ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [8]:
name_ratings = pd.merge(Books, Ratings, on='ISBN')

In [9]:
name_ratings.head(4)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,2,0
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,8,5
2,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11400,0
3,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11676,8

In [10]:
x = name_ratings.groupby('User-ID').count()['Book-Rating'] > 200
user_rating_count_df = x[x].index

In [11]:
user_rating_count_df

Int64Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,
              6323,   6543,
            ...
            271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427,
            277639, 278418],
           dtype='int64', name='User-ID', length=811)

In [12]:
filtered_ratings = name_ratings[name_ratings['User-ID'].isin(user_rating_count_df)]

In [13]:
filtered_ratings

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating
3,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11676,8
6,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,85526,0
7,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,96054,0
10,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,177458,0
21,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,110912,10
...,...,...,...,...,...,...,...,...,...,...
1031124,0231128444,Slow Food(The Case For Taste),Carlo Petrini,2003,Columbia University Press,http://images.amazon.com/images/P/0231128444.0...,http://images.amazon.com/images/P/0231128444.0...,http://images.amazon.com/images/P/0231128444.0...,275970,0
1031125,0520242335,Strong Democracy : Participatory Politics for ...,Benjamin R. Barber,2004,University of California Press,http://images.amazon.com/images/P/0520242335.0...,http://images.amazon.com/images/P/0520242335.0...,http://images.amazon.com/images/P/0520242335.0...,275970,0
1031126,0762412119,"Burpee Gardening Cyclopedia: A Concise, Up to ...",Allan Armitage,2002,Running Press Book Publishers,http://images.amazon.com/images/P/0762412119.0...,http://images.amazon.com/images/P/0762412119.0...,http://images.amazon.com/images/P/0762412119.0...,275970,0
1031127,1582380805,Tropical Rainforests: 230 Species in Full Colo...,"Allen M., Ph.D. Young",2001,Golden Guides from St. Martin's Press,http://images.amazon.com/images/P/1582380805.0...,http://images.amazon.com/images/P/1582380805.0...,http://images.amazon.com/images/P/1582380805.0...,275970,0
1031128,1845170423,Cocktail Classics,David Biggs,2004,Connaught,http://images.amazon.com/images/P/1845170423.0...,http://images.amazon.com/images/P/1845170423.0...,http://images.amazon.com/images/P/1845170423.0...,275970,7

In [14]:
y = filtered_ratings.groupby('Book-Title').count()['Book-Rating'] >= 50

In [15]:
popular_books_df = y[y].index

In [16]:
popular_books_df

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [17]:
final_ratings = filtered_ratings[filtered_ratings['Book-Title'].isin(popular_books_df)]

In [18]:
final_ratings

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating
31,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,11676,9
33,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,36836,0
34,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,46398,9
38,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,113270,0
39,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,113519,0
...,...,...,...,...,...,...,...,...,...,...
1028414,1878702831,Echoes,Nancy Morse,1992,Meteor Publishing Corporation,http://images.amazon.com/images/P/1878702831.0...,http://images.amazon.com/images/P/1878702831.0...,http://images.amazon.com/images/P/1878702831.0...,238781,0
1028600,0394429869,I Know Why the Caged Bird Sings,Maya Angelou,1996,Random House,http://images.amazon.com/images/P/0394429869.0...,http://images.amazon.com/images/P/0394429869.0...,http://images.amazon.com/images/P/0394429869.0...,239594,8
1028602,0449001164,The Promise,CHAIM POTOK,1997,Ballantine Books,http://images.amazon.com/images/P/0449001164.0...,http://images.amazon.com/images/P/0449001164.0...,http://images.amazon.com/images/P/0449001164.0...,239594,7
1028815,0743527631,The Pillars of the Earth,Ken Follett,2002,Encore,http://images.amazon.com/images/P/0743527631.0...,http://images.amazon.com/images/P/0743527631.0...,http://images.amazon.com/images/P/0743527631.0...,240144,0
1028817,0745168086,The Handmaid's Tale,Margaret Atwood,1999,Chivers Audio Books,http://images.amazon.com/images/P/0745168086.0...,http://images.amazon.com/images/P/0745168086.0...,http://images.amazon.com/images/P/0745168086.0...,240144,0

**Let's use the pivot table to display the (User-ID, Book-Title(Book-Rating))**

In [19]:
user_book_rating_pt = final_ratings.pivot_table(index='Book-Title', columns='User-ID', values='Book-Rating').fillna(0)

In [20]:
user_book_rating_pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

## Implementation of similarity using scikit-learn library

In [21]:
from sklearn.metrics.pairwise import cosine_similarity

In [22]:
similarity_scores = cosine_similarity(user_book_rating_pt)

In [23]:
similarity_scores.shape

(706, 706)

In [24]:
def recommend(book_title, recommendation_count):
    #if the book is not in the dataset, return
    if book_title not in user_book_rating_pt.index:
        print("Sorry!!! this book does not exist in the dataset!")
        return
    book_index = user_book_rating_pt.index.get_loc(book_title)
    similar_books = list(enumerate(similarity_scores[book_index]))
    similar_books = sorted(similar_books, key=lambda x:x[1], reverse=True)
    similar_books = similar_books[1:recommendation_count+1]
    # book_indices = [i[0] for i in similar_books]
    #return user_book_rating_pt.index[book_indices]
    # Print the names of the books with ordered list
    print(f'The top {recommendation_count} books similar to "{book_title}" are:' )
    i = 1
    for book in similar_books:
        print(str(i) + '. ' + user_book_rating_pt.index[book[0]])
        i += 1

In [25]:
recommend('The Lovely Bones: A Novel', 10)

The top 10 books similar to "The Lovely Bones: A Novel" are:
1. Where the Heart Is (Oprah's Book Club (Paperback))
2. Good in Bed
3. The Book of Ruth (Oprah's Book Club (Paperback))
4. Life of Pi
5. Lucky : A Memoir
6. The Pilot's Wife : A Novel
7. Drowning Ruth (Oprah's Book Club)
8. The Nanny Diaries: A Novel
9. Nights in Rodanthe
10. Empire Falls

In [26]:
book_name = input("Enter the name of the book: ")
recommendation_count = int(input("Enter the number of recommendations you want: "))
recommend(book_name, recommendation_count)

The top 20 books similar to "The Lovely Bones: A Novel" are:
1. Where the Heart Is (Oprah's Book Club (Paperback))
2. Good in Bed
3. The Book of Ruth (Oprah's Book Club (Paperback))
4. Life of Pi
5. Lucky : A Memoir
6. The Pilot's Wife : A Novel
7. Drowning Ruth (Oprah's Book Club)
8. The Nanny Diaries: A Novel
9. Nights in Rodanthe
10. Empire Falls
11. Confessions of an Ugly Stepsister : A Novel
12. How to Be Good
13. Suzanne's Diary for Nicholas
14. A Painted House
15. The Secret Life of Bees
16. Nickel and Dimed: On (Not) Getting By in America
17. White Oleander : A Novel (Oprah's Book Club)
18. The Da Vinci Code
19. Whispers
20. Midwives: A Novel


## Deployment Part

#### 1. Import and install dependencies

In [1]:
%pip install --upgrade pip

Requirement already satisfied: pip in c:\users\almud\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (22.3.1)Note: you may need to restart the kernel to use updated packages.

In [ ]:
#install ibm-watson-machine-learning
#%pip install ibm-watson-machine-learning
%pip install --upgrade --force-reinstall ibm-watson-machine-learning

In [4]:
from ibm_watson_machine_learning import APIClient
import json

#### 2. Authenticate and Set Space

#### 3. Save and Deploy Model

#### 4. Score Against Deployed Model